language: node_js
node_js:
  - '8'
  - '10'
  - '12'
addons:
  postgresql: 9.6
services:
  - postgresql
env:
  - NODE_ENV=test SECRET=travis
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install postgresql-9.6-postgis-2.3
before_script:
  - psql -U postgres -c 'create database biosentiers;'
  - psql -U postgres -c 'create extension postgis;' biosentiers
  - npm run migrate:test
after_success:
  - npm run test:coverage
